<?php


/**
 * @file
 * Send e-mail/SMS with contest code to registrees
 *
 */


/**
 * Implements hook_webform_submission_presave
 */
function hc_contest_webform_submission_presave($node, &$submission) {

  $mapping = _hc_contest_webform_mapping($node->webform['components']);

  // generate code and store it in webform component
  $code = _hc_contest_generate_code();
  $submission->data[$mapping['code']]['value'][0] = $code;

  // send e-mail
  $email = $submission->data[$mapping['e_mailadres']]['value'][0];

  // send sms
  $gsm = $submission->data[$mapping['gsm']]['value'][0];
  if ($gsm) {
    _hc_contest_send_sms($gsm, $code);
  }

}



/**
 * Helper function for mapping webform components
 */
function _hc_contest_webform_mapping($components) {
  $mapping = array();
  
  foreach ($components as $component) {
    $mapping[$component['form_key']] = $component['cid'];
  }
  
  return $mapping;
}



/**
 * Helper function for generating code
 */
function _hc_contest_generate_code($length = 8) {
  $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  $code = '';
  for ($i = 0; $i < $length; $i++) {
    $code .= $characters[rand(0, strlen($characters) - 1)];
  }
  return $code;
}

/**
 * Helper function for sending SMS
 */
function _hc_contest_send_sms($gsm, $code) {
  $gsm_stripped = substr($gsm, 1, 9);
  $gsm_full = "+32" . $gsm_stripped;

  $text = "Bedankt voor je inschrijving voor de Management Day. Je code is " . $code;
  
  $final_text = str_replace(" ", "+", $text);

  $url = "http://api.clickatell.com/http/sendmsg?user=gerrit1978&password=BVQFSSURIJbGDF&api_id=3412617&to=" . $gsm_full . "&text=" . $final_text;
  
  $ch = curl_init(); 
  curl_setopt($ch, CURLOPT_URL, $url); 
  $head = curl_exec($ch); 
  $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE); 
  curl_close($ch); 
  
   
}

/**
 * Implements hook_form_alter
 */
function hc_contest_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == 'webform_client_form_1') {
	  $form['#validate'][] = '_hc_contest_mobile_validate';
	}
}

/**
 * Helper validation function for mobile phone number
 */
function _hc_contest_mobile_validate(&$form, &$form_state) {
  $values = $form_state['values'];
  
  $mobile = $values['submitted']['right']['gsm'];
  
  if (!is_numeric($mobile) || substr($mobile, 0, 2) != "04" || strlen($mobile) != 10) {
    form_set_error('submitted][right][gsm', 'GSM-nummer moet in het juiste formaat staan: 04xxxxxxxx');
    return false;
  } else {
    return true;
  }
}