<?php


/**
 * @file
 *  Send e-mail/SMS with contest code to registrees
 *
 */


/**
 * Implements hook_webform_submission_presave
 */
function hc_contest_webform_submission_presave($node, &$submission) {

  $mapping = _hc_contest_webform_mapping($node->webform['components']);

	// generate code and store it in webform component
	$code = _hc_contest_generate_code();
	$submission->data[$mapping['code']]['value'][0] = $code;

	
	// send e-mail
	$email = $submission->data[$mapping['e_mailadres']]['value'][0];



	// send sms
	$gsm = $submission->data[$mapping['gsm']]['value'][0];
	if ($gsm) {
	  _hc_contest_send_sms($gsm);
	}


}



/**
 * Helper function for mapping webform components
 */
function _hc_contest_webform_mapping($components) {
  $mapping = array();
  
  foreach ($components as $component) {
    $mapping[$component['form_key']] = $component['cid']	;
  }
  
  return $mapping;
}



/**
 * Helper function for generating code
 */
function _hc_contest_generate_code($length = 8) {
	$characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
	$code = '';
	for ($i = 0; $i < $length; $i++) {
	  $code .= $characters[rand(0, strlen($characters) - 1)];
	}
	return $code;
}

/**
 * Helper function for sending SMS
 */
function _hc_contest_send_sms($gsm) {
  $url = "http://api.clickatell.com/http/sendmsg?user=gerrit1978&password=BVQFSSURIJbGDF&api_id=3412617&to=" . $gsm . "&text=Meet+me+outside";
  
  $ch = curl_init(); 
  curl_setopt($ch, CURLOPT_URL, $url); 
  $head = curl_exec($ch); 
  $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE); 
  curl_close($ch); 
  
  print $httpCode;
  exit();
   
}